export const flagsNameCountryCode = [
  {
    countryName: 'Afghanistan',
    regionCode: 'AF',
    countryId: 'afghanistan',
    countryPrefix: 93,
  },
  {
    countryName: 'Albania',
    regionCode: 'AL',
    countryId: 'albania',
    countryPrefix: 355,
  },
  {
    countryName: 'Algeria',
    regionCode: 'DZ',
    countryId: 'algeria',
    countryPrefix: 213,
  },
  {
    countryName: 'American Samoa',
    countryId: 'american-samoa',
    regionCode: 'AS',
    countryPrefix: 1,
  },
  {
    countryName: 'Andorra',
    regionCode: 'AD',
    countryId: 'andorra',
    countryPrefix: 376,
  },
  {
    countryName: 'Angola',
    regionCode: 'AO',
    countryId: 'angola',
    countryPrefix: 244,
  },
  {
    countryName: 'Anguilla',
    regionCode: 'AI',
    countryId: 'anguilla',
    countryPrefix: 1,
  },
  {
    countryName: 'Antigua and Barbuda',
    countryId: 'antigua-and-barbuda',
    regionCode: 'AG',
    countryPrefix: 1,
  },
  {
    countryName: 'Argentina',
    regionCode: 'AR',
    countryId: 'argentina',
    countryPrefix: 54,
  },
  {
    countryName: 'Armenia',
    regionCode: 'AM',
    countryId: 'armenia',
    countryPrefix: 374,
  },
  {
    countryName: 'Aruba',
    regionCode: 'AW',
    countryId: 'aruba',
    countryPrefix: 297,
  },
  {
    countryName: 'Australia',
    regionCode: 'AU',
    countryId: 'australia',
    countryPrefix: 61,
  },
  {
    countryName: 'Austria',
    regionCode: 'AT',
    countryId: 'austria',
    countryPrefix: 43,
  },
  {
    countryName: 'Azerbaijan',
    regionCode: 'AZ',
    countryId: 'azerbaijan',
    countryPrefix: 994,
  },
  {
    countryName: 'Bahamas',
    regionCode: 'BS',
    countryId: 'bahamas',
    countryPrefix: 1,
  },
  {
    countryName: 'Bahrain',
    regionCode: 'BH',
    countryId: 'bahrain',
    countryPrefix: 973,
  },
  {
    countryName: 'Bangladesh',
    regionCode: 'BD',
    countryId: 'bangladesh',
    countryPrefix: 880,
  },
  {
    countryName: 'Barbados',
    regionCode: 'BB',
    countryId: 'barbados',
    countryPrefix: 1,
  },
  {
    countryName: 'Belarus',
    regionCode: 'BY',
    countryId: 'belarus',
    countryPrefix: 375,
  },
  {
    countryName: 'Belgium',
    regionCode: 'BE',
    countryId: 'belgium',
    countryPrefix: 32,
  },
  {
    countryName: 'Belize',
    regionCode: 'BZ',
    countryId: 'belize',
    countryPrefix: 501,
  },
  {
    countryName: 'Benin',
    regionCode: 'BJ',
    countryId: 'benin',
    countryPrefix: 229,
  },
  {
    countryName: 'Bermuda',
    regionCode: 'BM',
    countryId: 'bermuda',
    countryPrefix: 1,
  },
  {
    countryName: 'Bhutan',
    regionCode: 'BT',
    countryId: 'bhutan',
    countryPrefix: 975,
  },
  {
    countryName: 'Bolivia',
    regionCode: 'BO',
    countryId: 'bolivia',
    countryPrefix: 591,
  },
  {
    countryName: 'Bosnia and Herzegovina',
    countryId: 'bosnia-and-herzegovina',
    regionCode: 'BA',
    countryPrefix: 387,
  },
  {
    countryName: 'Botswana',
    regionCode: 'BW',
    countryId: 'botswana',
    countryPrefix: 267,
  },
  {
    countryName: 'Brazil',
    regionCode: 'BR',
    countryId: 'brazil',
    countryPrefix: 55,
  },
  {
    countryName: 'British Indian Ocean Territory',
    countryId: 'british-indian-ocean-territory',
    regionCode: 'IO',
    countryPrefix: 246,
  },
  {
    countryName: 'British Virgin Islands',
    countryId: 'british-virgin-islands',
    regionCode: 'VG',
    countryPrefix: 1,
  },
  {
    countryName: 'Brunei',
    regionCode: 'BN',
    countryId: 'brunei',
    countryPrefix: 673,
  },
  {
    countryName: 'Bulgaria',
    regionCode: 'BG',
    countryId: 'bulgaria',
    countryPrefix: 359,
  },
  {
    countryName: 'Burkina Faso',
    countryId: 'burkina-faso',
    regionCode: 'BF',
    countryPrefix: 226,
  },
  {
    countryName: 'Myanmar',
    regionCode: 'MM',
    countryId: 'myanmar',
    countryPrefix: 95,
  },
  {
    countryName: 'Burundi',
    regionCode: 'BI',
    countryId: 'burundi',
    countryPrefix: 257,
  },
  {
    countryName: 'Cambodia',
    regionCode: 'KH',
    countryId: 'cambodia',
    countryPrefix: 855,
  },
  {
    countryName: 'Cameroon',
    regionCode: 'CM',
    countryId: 'cameroon',
    countryPrefix: 237,
  },
  {
    countryName: 'Canada',
    regionCode: 'CA',
    countryId: 'canada',
    countryPrefix: 1,
  },
  {
    countryName: 'Cape Verde',
    countryId: 'cape-verde',
    regionCode: 'CV',
    countryPrefix: 238,
  },
  {
    countryName: 'Cayman Islands',
    countryId: 'cayman-islands',
    regionCode: 'KY',
    countryPrefix: 1,
  },
  {
    countryName: 'Central African Republic',
    regionCode: 'CF',
    countryId: 'central-african-republic',
    countryPrefix: 236,
  },
  {
    countryName: 'Chad',
    regionCode: 'TD',
    countryId: 'chad',
    countryPrefix: 235,
  },
  {
    countryName: 'Chile',
    regionCode: 'CL',
    countryId: 'chile',
    countryPrefix: 56,
  },
  {
    countryName: 'China',
    regionCode: 'CN',
    countryId: 'china',
    countryPrefix: 86,
  },
  {
    countryName: 'Christmas Island',
    regionCode: 'CX',
    countryId: 'christmas-island',
    countryPrefix: 61,
  },
  {
    countryName: 'Cocos Islands',
    regionCode: 'CC',
    countryId: 'cocos-islands',
    countryPrefix: 61,
  },
  {
    countryName: 'Colombia',
    regionCode: 'CO',
    countryId: 'colombia',
    countryPrefix: 57,
  },
  {
    countryName: 'Comoros',
    regionCode: 'KM',
    countryId: 'comoros',
    countryPrefix: 269,
  },
  {
    countryName: 'Republic of the Congo',
    regionCode: 'CG',
    countryId: 'republic-of-the-congo',
    countryPrefix: 242,
  },
  {
    countryName: 'Democratic Republic of the Congo',
    regionCode: 'CD',
    countryId: 'democratic-republic-of-the-congo',
    countryPrefix: 243,
  },
  {
    countryName: 'Cook Islands',
    regionCode: 'CK',
    countryId: 'cook-islands',
    countryPrefix: 682,
  },
  {
    countryName: 'Costa Rica',
    regionCode: 'CR',
    countryId: 'costa-rica',
    countryPrefix: 506,
  },
  {
    countryName: 'Croatia',
    regionCode: 'HR',
    countryId: 'croatia',
    countryPrefix: 385,
  },
  {
    countryName: 'Cuba',
    regionCode: 'CU',
    countryId: 'cuba',
    countryPrefix: 53,
  },
  {
    countryName: 'Curacao',
    regionCode: 'CW',
    countryId: 'curacao',
    countryPrefix: 599,
  },
  {
    countryName: 'Cyprus',
    regionCode: 'CY',
    countryId: 'cyprus',
    countryPrefix: 357,
  },
  {
    countryName: 'Czech Republic',
    regionCode: 'CZ',
    countryId: 'czech-republic',
    countryPrefix: 420,
  },
  {
    countryName: 'Denmark',
    regionCode: 'DK',
    countryId: 'denmark',
    countryPrefix: 45,
  },
  {
    countryName: 'Djibouti',
    regionCode: 'DJ',
    countryId: 'djibouti',
    countryPrefix: 253,
  },
  {
    countryName: 'Dominica',
    regionCode: 'DM',
    countryId: 'dominica',
    countryPrefix: 1,
  },
  {
    countryName: 'Dominican Republic',
    regionCode: 'DO',
    countryId: 'dominican-republic',
    countryPrefix: 1,
  },
  {
    countryName: 'Dominican Republic',
    regionCode: 'DO',
    countryId: 'dominican-republic',
    countryPrefix: 1,
  },
  {
    countryName: 'Dominican Republic',
    regionCode: 'DO',
    countryId: 'dominican-republic',
    countryPrefix: 1,
  },
  {
    countryName: 'East Timor',
    regionCode: 'TL',
    countryId: 'east-timor',
    countryPrefix: 670,
  },
  {
    countryName: 'Ecuador',
    regionCode: 'EC',
    countryId: 'ecuador',
    countryPrefix: 593,
  },
  {
    countryName: 'Egypt',
    regionCode: 'EG',
    countryId: 'egypt',
    countryPrefix: 20,
  },
  {
    countryName: 'El Salvador',
    regionCode: 'SV',
    countryId: 'el-salvador',
    countryPrefix: 503,
  },
  {
    countryName: 'Equatorial Guinea',
    regionCode: 'GQ',
    countryId: 'equatorial-guinea',
    countryPrefix: 240,
  },
  {
    countryName: 'Eritrea',
    regionCode: 'ER',
    countryId: 'eritrea',
    countryPrefix: 291,
  },
  {
    countryName: 'Estonia',
    regionCode: 'EE',
    countryId: 'estonia',
    countryPrefix: 372,
  },
  {
    countryName: 'Ethiopia',
    regionCode: 'ET',
    countryId: 'ethiopia',
    countryPrefix: 251,
  },
  {
    countryName: 'Falkland Islands',
    regionCode: 'FK',
    countryId: 'falkland-islands',
    countryPrefix: 500,
  },
  {
    countryName: 'Faroe Islands',
    regionCode: 'FO',
    countryId: 'faroe-islands',
    countryPrefix: 298,
  },
  {
    countryName: 'Fiji',
    regionCode: 'FJ',
    countryId: 'fiji',
    countryPrefix: 679,
  },
  {
    countryName: 'Finland',
    regionCode: 'FI',
    countryId: 'finland',
    countryPrefix: 358,
  },
  {
    countryName: 'France',
    regionCode: 'FR',
    countryId: 'france',
    countryPrefix: 33,
  },
  {
    countryName: 'French Polynesia',
    regionCode: 'PF',
    countryId: 'french-polynesia',
    countryPrefix: 689,
  },
  {
    countryName: 'Gabon',
    regionCode: 'GA',
    countryId: 'gabon',
    countryPrefix: 241,
  },
  {
    countryName: 'Gambia',
    regionCode: 'GM',
    countryId: 'gambia',
    countryPrefix: 220,
  },
  {
    countryName: 'Georgia',
    regionCode: 'GE',
    countryId: 'georgia',
    countryPrefix: 995,
  },
  {
    countryName: 'Germany',
    regionCode: 'DE',
    countryId: 'germany',
    countryPrefix: 49,
  },
  {
    countryName: 'Ghana',
    regionCode: 'GH',
    countryId: 'ghana',
    countryPrefix: 233,
  },
  {
    countryName: 'Gibraltar',
    regionCode: 'GI',
    countryId: 'gibraltar',
    countryPrefix: 350,
  },
  {
    countryName: 'Greece',
    regionCode: 'GR',
    countryId: 'greece',
    countryPrefix: 30,
  },
  {
    countryName: 'Greenland',
    regionCode: 'GL',
    countryId: 'greenland',
    countryPrefix: 299,
  },
  {
    countryName: 'Grenada',
    regionCode: 'GD',
    countryId: 'grenada',
    countryPrefix: 1,
  },
  {
    countryName: 'Guam',
    regionCode: 'GU',
    countryId: 'guam',
    countryPrefix: 1,
  },
  {
    countryName: 'Guatemala',
    regionCode: 'GT',
    countryId: 'guatemala',
    countryPrefix: 502,
  },
  {
    countryName: 'Guernsey',
    regionCode: 'GG',
    countryId: 'guernsey',
    countryPrefix: 44,
  },
  {
    countryName: 'Guinea',
    regionCode: 'GN',
    countryId: 'guinea',
    countryPrefix: 224,
  },
  {
    countryName: 'Guinea-Bissau',
    regionCode: 'GW',
    countryId: 'guinea-bissau',
    countryPrefix: 245,
  },
  {
    countryName: 'Guyana',
    regionCode: 'GY',
    countryId: 'guyana',
    countryPrefix: 592,
  },
  {
    countryName: 'Haiti',
    regionCode: 'HT',
    countryId: 'haiti',
    countryPrefix: 509,
  },
  {
    countryName: 'Honduras',
    regionCode: 'HN',
    countryId: 'honduras',
    countryPrefix: 504,
  },
  {
    countryName: 'Hong Kong',
    regionCode: 'HK',
    countryId: 'hong-kong',
    countryPrefix: 852,
  },
  {
    countryName: 'Hungary',
    regionCode: 'HU',
    countryId: 'hungary',
    countryPrefix: 36,
  },
  {
    countryName: 'Iceland',
    regionCode: 'IS',
    countryId: 'iceland',
    countryPrefix: 354,
  },
  {
    countryName: 'India',
    regionCode: 'IN',
    countryId: 'india',
    countryPrefix: 91,
  },
  {
    countryName: 'Indonesia',
    regionCode: 'ID',
    countryId: 'indonesia',
    countryPrefix: 62,
  },
  {
    countryName: 'Iran',
    regionCode: 'IR',
    countryId: 'iran',
    countryPrefix: 98,
  },
  {
    countryName: 'Iraq',
    regionCode: 'IQ',
    countryId: 'iraq',
    countryPrefix: 964,
  },
  {
    countryName: 'Ireland',
    regionCode: 'IE',
    countryId: 'ireland',
    countryPrefix: 353,
  },
  {
    countryName: 'Isle of Man',
    regionCode: 'IM',
    countryId: 'isle-of-man',
    countryPrefix: 44,
  },
  {
    countryName: 'Israel',
    regionCode: 'IL',
    countryId: 'israel',
    countryPrefix: 972,
  },
  {
    countryName: 'Italy',
    regionCode: 'IT',
    countryId: 'italy',
    countryPrefix: 39,
  },
  {
    countryName: 'Ivory Coast',
    regionCode: 'CI',
    countryId: 'ivory-coast',
    countryPrefix: 225,
  },
  {
    countryName: 'Jamaica',
    regionCode: 'JM',
    countryId: 'jamaica',
    countryPrefix: 1,
  },
  {
    countryName: 'Japan',
    regionCode: 'JP',
    countryId: 'japan',
    countryPrefix: 81,
  },
  {
    countryName: 'Jersey',
    regionCode: 'JE',
    countryId: 'jersey',
    countryPrefix: 44,
  },
  {
    countryName: 'Jordan',
    regionCode: 'JO',
    countryId: 'jordan',
    countryPrefix: 962,
  },
  {
    countryName: 'Kazakhstan',
    regionCode: 'KZ',
    countryId: 'kazakhstan',
    countryPrefix: 7,
  },
  {
    countryName: 'Kenya',
    regionCode: 'KE',
    countryId: 'kenya',
    countryPrefix: 254,
  },
  {
    countryName: 'Kiribati',
    regionCode: 'KI',
    countryId: 'kiribati',
    countryPrefix: 686,
  },
  {
    countryName: 'Kosovo',
    regionCode: 'XK',
    countryId: 'kosovo',
    countryPrefix: 383,
  },
  {
    countryName: 'Kuwait',
    regionCode: 'KW',
    countryId: 'kuwait',
    countryPrefix: 965,
  },
  {
    countryName: 'Kyrgyzstan',
    regionCode: 'KG',
    countryId: 'kyrgyzstan',
    countryPrefix: 996,
  },
  {
    countryName: 'Laos',
    regionCode: 'LA',
    countryId: 'laos',
    countryPrefix: 856,
  },
  {
    countryName: 'Latvia',
    regionCode: 'LV',
    countryId: 'latvia',
    countryPrefix: 371,
  },
  {
    countryName: 'Lebanon',
    regionCode: 'LB',
    countryId: 'lebanon',
    countryPrefix: 961,
  },
  {
    countryName: 'Lesotho',
    regionCode: 'LS',
    countryId: 'lesotho',
    countryPrefix: 266,
  },
  {
    countryName: 'Liberia',
    regionCode: 'LR',
    countryId: 'liberia',
    countryPrefix: 231,
  },
  {
    countryName: 'Libya',
    regionCode: 'LY',
    countryId: 'libya',
    countryPrefix: 218,
  },
  {
    countryName: 'Liechtenstein',
    regionCode: 'LI',
    countryId: 'liechtenstein',
    countryPrefix: 423,
  },
  {
    countryName: 'Lithuania',
    regionCode: 'LT',
    countryId: 'lithuania',
    countryPrefix: 370,
  },
  {
    countryName: 'Luxembourg',
    regionCode: 'LU',
    countryId: 'luxembourg',
    countryPrefix: 352,
  },
  {
    countryName: 'Macau',
    regionCode: 'MO',
    countryId: 'macau',
    countryPrefix: 853,
  },
  {
    countryName: 'Macedonia',
    regionCode: 'MK',
    countryId: 'macedonia',
    countryPrefix: 389,
  },
  {
    countryName: 'Madagascar',
    regionCode: 'MG',
    countryId: 'madagascar',
    countryPrefix: 261,
  },
  {
    countryName: 'Malawi',
    regionCode: 'MW',
    countryId: 'malawi',
    countryPrefix: 265,
  },
  {
    countryName: 'Malaysia',
    regionCode: 'MY',
    countryId: 'malaysia',
    countryPrefix: 60,
  },
  {
    countryName: 'Maldives',
    regionCode: 'MV',
    countryId: 'maldives',
    countryPrefix: 960,
  },
  {
    countryName: 'Mali',
    regionCode: 'ML',
    countryId: 'mali',
    countryPrefix: 223,
  },
  {
    countryName: 'Malta',
    regionCode: 'MT',
    countryId: 'malta',
    countryPrefix: 356,
  },
  {
    countryName: 'Marshall Islands',
    regionCode: 'MH',
    countryId: 'marshall-islands',
    countryPrefix: 692,
  },
  {
    countryName: 'Mauritania',
    regionCode: 'MR',
    countryId: 'mauritania',
    countryPrefix: 222,
  },
  {
    countryName: 'Mauritius',
    regionCode: 'MU',
    countryId: 'mauritius',
    countryPrefix: 230,
  },
  {
    countryName: 'Mayotte',
    regionCode: 'YT',
    countryId: 'mayotte',
    countryPrefix: 262,
  },
  {
    countryName: 'Mexico',
    regionCode: 'MX',
    countryId: 'mexico',
    countryPrefix: 52,
  },
  {
    countryName: 'Micronesia',
    regionCode: 'FM',
    countryId: 'micronesia',
    countryPrefix: 691,
  },
  {
    countryName: 'Moldova',
    regionCode: 'MD',
    countryId: 'moldova',
    countryPrefix: 373,
  },
  {
    countryName: 'Monaco',
    regionCode: 'MC',
    countryId: 'monaco',
    countryPrefix: 377,
  },
  {
    countryName: 'Mongolia',
    regionCode: 'MN',
    countryId: 'mongolia',
    countryPrefix: 976,
  },
  {
    countryName: 'Montenegro',
    regionCode: 'ME',
    countryId: 'montenegro',
    countryPrefix: 382,
  },
  {
    countryName: 'Montserrat',
    regionCode: 'MS',
    countryId: 'montserrat',
    countryPrefix: 1,
  },
  {
    countryName: 'Morocco',
    regionCode: 'MA',
    countryId: 'morocco',
    countryPrefix: 212,
  },
  {
    countryName: 'Mozambique',
    regionCode: 'MZ',
    countryId: 'mozambique',
    countryPrefix: 258,
  },
  {
    countryName: 'Namibia',
    regionCode: 'NA',
    countryId: 'namibia',
    countryPrefix: 264,
  },
  {
    countryName: 'Nauru',
    regionCode: 'NR',
    countryId: 'nauru',
    countryPrefix: 674,
  },
  {
    countryName: 'Nepal',
    regionCode: 'NP',
    countryId: 'nepal',
    countryPrefix: 977,
  },
  {
    countryName: 'Netherlands',
    regionCode: 'NL',
    countryId: 'netherlands',
    countryPrefix: 31,
  },
  {
    countryName: 'New Caledonia',
    regionCode: 'NC',
    countryId: 'new-caledonia',
    countryPrefix: 687,
  },
  {
    countryName: 'New Zealand',
    regionCode: 'NZ',
    countryId: 'new-zealand',
    countryPrefix: 64,
  },
  {
    countryName: 'Nicaragua',
    regionCode: 'NI',
    countryId: 'nicaragua',
    countryPrefix: 505,
  },
  {
    countryName: 'Niger',
    regionCode: 'NE',
    countryId: 'niger',
    countryPrefix: 227,
  },
  {
    countryName: 'Nigeria',
    regionCode: 'NG',
    countryId: 'nigeria',
    countryPrefix: 234,
  },
  {
    countryName: 'Niue',
    regionCode: 'NU',
    countryId: 'niue',
    countryPrefix: 683,
  },
  {
    countryName: 'Northern Mariana Islands',
    regionCode: 'MP',
    countryId: 'northern-mariana-islands',
    countryPrefix: 1,
  },
  {
    countryName: 'North Korea',
    regionCode: 'KP',
    countryId: 'north-korea',
    countryPrefix: 850,
  },
  {
    countryName: 'Norway',
    regionCode: 'NO',
    countryId: 'norway',
    countryPrefix: 47,
  },
  {
    countryName: 'Oman',
    regionCode: 'OM',
    countryId: 'oman',
    countryPrefix: 968,
  },
  {
    countryName: 'Pakistan',
    regionCode: 'PK',
    countryId: 'pakistan',
    countryPrefix: 92,
  },
  {
    countryName: 'Palau',
    regionCode: 'PW',
    countryId: 'palau',
    countryPrefix: 680,
  },
  {
    countryName: 'Palestine',
    regionCode: 'PS',
    countryId: 'palestine',
    countryPrefix: 970,
  },
  {
    countryName: 'Panama',
    regionCode: 'PA',
    countryId: 'panama',
    countryPrefix: 507,
  },
  {
    countryName: 'Papua New Guinea',
    regionCode: 'PG',
    countryId: 'papua-new-guinea',
    countryPrefix: 675,
  },
  {
    countryName: 'Paraguay',
    regionCode: 'PY',
    countryId: 'paraguay',
    countryPrefix: 595,
  },
  {
    countryName: 'Peru',
    regionCode: 'PE',
    countryId: 'peru',
    countryPrefix: 51,
  },
  {
    countryName: 'Philippines',
    regionCode: 'PH',
    countryId: 'philippines',
    countryPrefix: 63,
  },
  {
    countryName: 'Poland',
    regionCode: 'PL',
    countryId: 'poland',
    countryPrefix: 48,
  },
  {
    countryName: 'Portugal',
    regionCode: 'PT',
    countryId: 'portugal',
    countryPrefix: 351,
  },
  {
    countryName: 'Puerto Rico',
    regionCode: 'PR',
    countryId: 'puerto-rico',
    countryPrefix: 1,
  },
  {
    countryName: 'Puerto Rico',
    regionCode: 'PR',
    countryId: 'puerto-rico',
    countryPrefix: 1,
  },
  {
    countryName: 'Qatar',
    regionCode: 'QA',
    countryId: 'qatar',
    countryPrefix: 974,
  },
  {
    countryName: 'Reunion',
    regionCode: 'RE',
    countryId: 'reunion',
    countryPrefix: 262,
  },
  {
    countryName: 'Romania',
    regionCode: 'RO',
    countryId: 'romania',
    countryPrefix: 40,
  },
  {
    countryName: 'Russia',
    regionCode: 'RU',
    countryId: 'russia',
    countryPrefix: 7,
  },
  {
    countryName: 'Rwanda',
    regionCode: 'RW',
    countryId: 'rwanda',
    countryPrefix: 250,
  },
  {
    countryName: 'Samoa',
    regionCode: 'WS',
    countryId: 'samoa',
    countryPrefix: 685,
  },
  {
    countryName: 'San Marino',
    regionCode: 'SM',
    countryId: 'san-marino',
    countryPrefix: 378,
  },
  {
    countryName: 'Sao Tome and Principe',
    regionCode: 'ST',
    countryId: 'sao-tome-and-principe',
    countryPrefix: 239,
  },
  {
    countryName: 'Saudi Arabia',
    regionCode: 'SA',
    countryId: 'saudi-arabia',
    countryPrefix: 966,
  },
  {
    countryName: 'Senegal',
    regionCode: 'SN',
    countryId: 'senegal',
    countryPrefix: 221,
  },
  {
    countryName: 'Serbia',
    regionCode: 'RS',
    countryId: 'serbia',
    countryPrefix: 381,
  },
  {
    countryName: 'Seychelles',
    regionCode: 'SC',
    countryId: 'seychelles',
    countryPrefix: 248,
  },
  {
    countryName: 'Sierra Leone',
    regionCode: 'SL',
    countryId: 'sierra-leone',
    countryPrefix: 232,
  },
  {
    countryName: 'Singapore',
    regionCode: 'SG',
    countryId: 'singapore',
    countryPrefix: 65,
  },
  {
    countryName: 'Sint Maarten',
    regionCode: 'SX',
    countryId: 'sint-maarten',
    countryPrefix: 1,
  },
  {
    countryName: 'Slovakia',
    regionCode: 'SK',
    countryId: 'slovakia',
    countryPrefix: 421,
  },
  {
    countryName: 'Slovenia',
    regionCode: 'SI',
    countryId: 'slovenia',
    countryPrefix: 386,
  },
  {
    countryName: 'Solomon Islands',
    regionCode: 'SB',
    countryId: 'solomon-islands',
    countryPrefix: 677,
  },
  {
    countryName: 'Somalia',
    regionCode: 'SO',
    countryId: 'somalia',
    countryPrefix: 252,
  },
  {
    countryName: 'South Africa',
    regionCode: 'ZA',
    countryId: 'south-africa',
    countryPrefix: 27,
  },
  {
    countryName: 'South Korea',
    regionCode: 'KR',
    countryId: 'south-korea',
    countryPrefix: 82,
  },
  {
    countryName: 'South Sudan',
    regionCode: 'SS',
    countryId: 'south-sudan',
    countryPrefix: 211,
  },
  {
    countryName: 'Spain',
    regionCode: 'ES',
    countryId: 'spain',
    countryPrefix: 34,
  },
  {
    countryName: 'Sri Lanka',
    regionCode: 'LK',
    countryId: 'sri-lanka',
    countryPrefix: 94,
  },
  {
    countryName: 'Saint Helena',
    regionCode: 'SH',
    countryId: 'saint-helena',
    countryPrefix: 290,
  },
  {
    countryName: 'Saint Kitts and Nevis',
    regionCode: 'KN',
    countryId: 'saint-kitts-and-nevis',
    countryPrefix: 1,
  },
  {
    countryName: 'Saint Lucia',
    regionCode: 'LC',
    countryId: 'saint-lucia',
    countryPrefix: 1,
  },
  {
    countryName: 'Saint Martin',
    regionCode: 'MF',
    countryId: 'saint-martin',
    countryPrefix: 590,
  },
  {
    countryName: 'Saint Pierre and Miquelon',
    regionCode: 'PM',
    countryId: 'saint-pierre-and-miquelon',
    countryPrefix: 508,
  },
  {
    countryName: 'Saint Vincent and the Grenadines',
    regionCode: 'VC',
    countryId: 'saint-vincent-and-the-grenadines',
    countryPrefix: 1,
  },
  {
    countryName: 'Sudan',
    regionCode: 'SD',
    countryId: 'sudan',
    countryPrefix: 249,
  },
  {
    countryName: 'SuricountryName',
    regionCode: 'SR',
    countryId: 'suricountryname',
    countryPrefix: 597,
  },
  {
    countryName: 'Svalbard and Jan Mayen',
    regionCode: 'SJ',
    countryId: 'svalbard-and-jan-mayen',
    countryPrefix: 47,
  },
  {
    countryName: 'Swaziland',
    regionCode: 'SZ',
    countryId: 'swaziland',
    countryPrefix: 268,
  },
  {
    countryName: 'Sweden',
    regionCode: 'SE',
    countryId: 'sweden',
    countryPrefix: 46,
  },
  {
    countryName: 'Switzerland',
    regionCode: 'CH',
    countryId: 'switzerland',
    countryPrefix: 41,
  },
  {
    countryName: 'Syria',
    regionCode: 'SY',
    countryId: 'syria',
    countryPrefix: 963,
  },
  {
    countryName: 'Taiwan',
    regionCode: 'TW',
    countryId: 'taiwan',
    countryPrefix: 886,
  },
  {
    countryName: 'Tajikistan',
    regionCode: 'TJ',
    countryId: 'tajikistan',
    countryPrefix: 992,
  },
  {
    countryName: 'Tanzania',
    regionCode: 'TZ',
    countryId: 'tanzania',
    countryPrefix: 255,
  },
  {
    countryName: 'Thailand',
    regionCode: 'TH',
    countryId: 'thailand',
    countryPrefix: 66,
  },
  {
    countryName: 'Togo',
    regionCode: 'TG',
    countryId: 'togo',
    countryPrefix: 228,
  },
  {
    countryName: 'Tokelau',
    regionCode: 'TK',
    countryId: 'tokelau',
    countryPrefix: 690,
  },
  {
    countryName: 'Tonga',
    regionCode: 'TO',
    countryId: 'tonga',
    countryPrefix: 676,
  },
  {
    countryName: 'Trinidad and Tobago',
    regionCode: 'TT',
    countryId: 'trinidad-and-tobago',
    countryPrefix: 1,
  },
  {
    countryName: 'Tunisia',
    regionCode: 'TN',
    countryId: 'tunisia',
    countryPrefix: 216,
  },
  {
    countryName: 'Turkey',
    regionCode: 'TR',
    countryId: 'turkey',
    countryPrefix: 90,
  },
  {
    countryName: 'Turkmenistan',
    regionCode: 'TM',
    countryId: 'turkmenistan',
    countryPrefix: 993,
  },
  {
    countryName: 'Turks and Caicos Islands',
    regionCode: 'TC',
    countryId: 'turks-and-caicos-islands',
    countryPrefix: 1,
  },
  {
    countryName: 'Tuvalu',
    regionCode: 'TV',
    countryId: 'tuvalu',
    countryPrefix: 688,
  },
  {
    countryName: 'United Arab Emirates',
    regionCode: 'AE',
    countryId: 'united-arab-emirates',
    countryPrefix: 971,
  },
  {
    countryName: 'Uganda',
    regionCode: 'UG',
    countryId: 'uganda',
    countryPrefix: 256,
  },
  {
    countryName: 'United Kingdom',
    regionCode: 'GB',
    countryId: 'united-kingdom',
    countryPrefix: 44,
  },
  {
    countryName: 'Ukraine',
    regionCode: 'UA',
    countryId: 'ukraine',
    countryPrefix: 380,
  },
  {
    countryName: 'Uruguay',
    regionCode: 'UY',
    countryId: 'uruguay',
    countryPrefix: 598,
  },
  {
    countryName: 'United States',
    regionCode: 'US',
    countryId: 'united-states',
    countryPrefix: 1,
  },
  {
    countryName: 'Uzbekistan',
    regionCode: 'UZ',
    countryId: 'uzbekistan',
    countryPrefix: 998,
  },
  {
    countryName: 'Vanuatu',
    regionCode: 'VU',
    countryId: 'vanuatu',
    countryPrefix: 678,
  },
  {
    countryName: 'Vatican',
    regionCode: 'VA',
    countryId: 'vatican',
    countryPrefix: 39,
  },
  {
    countryName: 'Venezuela',
    regionCode: 'VE',
    countryId: 'venezuela',
    countryPrefix: 58,
  },
  {
    countryName: 'Vietnam',
    regionCode: 'VN',
    countryId: 'vietnam',
    countryPrefix: 84,
  },
  {
    countryName: 'U.S. Virgin Islands',
    regionCode: 'VI',
    countryId: 'u.s.-virgin-islands',
    countryPrefix: 1,
  },
  {
    countryName: 'Wallis and Futuna',
    regionCode: 'WF',
    countryId: 'wallis-and-futuna',
    countryPrefix: 681,
  },
  {
    countryName: 'Western Sahara',
    regionCode: 'EH',
    countryId: 'western-sahara',
    countryPrefix: 212,
  },
  {
    countryName: 'Yemen',
    regionCode: 'YE',
    countryId: 'yemen',
    countryPrefix: 967,
  },
  {
    countryName: 'Zambia',
    regionCode: 'ZM',
    countryId: 'zambia',
    countryPrefix: 260,
  },
  {
    countryName: 'Zimbabwe',
    regionCode: 'ZW',
    countryId: 'zimbabwe',
    countryPrefix: 263,
  },
];
